
#for the navbar links.
custom_links:
  - title: Agent Mastermind
    url: https://themarketinganimals.net/agentmastermind/?affiliate=0
  - title: Member Login
    url: http://www.mortgagemarketinganimals.com/agentmastermind/login/

#site settings
title: Agent Mastermind
description: 'Welcome To The Ultimate Shortcut to more Referral Partners, deeper relationships, more referrals and more closings!!'

#controls all the site info
client:
  market:
  name: Scott Hudspeth
  brand: Agent Mastermind
  brokerage:
  address:
  phone: 1-727-787-2275
  email: Support@AgentMastermind.com
  url: https://themarketinganimals.net
  # if forms put '/homevalue/' or '/homesearch/'
  cta1: '/homevalue/'
  cta2: '/homesearch/'
  VR_form: 'http://oi.vresp.com?fid=f84bc70f7d'

# social links
socials:
  facebook: 'https://www.facebook.com/agentmastermind/'
  linkedin: 'https://www.linkedin.com/in/scotthudspeth'
  gplus: 'https://plus.google.com/111680897236247745053'
  youtube: 'https://www.youtube.com/channel/UCDozQXVeCTf0a9LRu6aXoSQ?nohtml5=False'
  twitter: 'https://twitter.com/scotthudspethmi'
  instagram: '#'
  pinterest: '#'
  zillow: '#'
  trulia: '#'
  yelp: '#'
  podcast: '#'

#podcast settings
podcast:
  title: San Francisco Real Estate Podcast
  categories:
    - category: 'News &amp; Politics'
  image: 'http://i.imgur.com/jJxfq9v.jpg'
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Francisco Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Durwin Homes Group - your professional San Francisco Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Durwin Cheung

#layout options
review_sm_icons: true
audit_header: false

#image settings
images:
  hero_image_path: /img/tiger_on_black.jpg
  hero_logo_path: /img/Durwin_logo_white.png
  hero_background_hex: '#000'
  client_headshot_path: /img/scottspic.jpg

#colors
brand_hex: "#F58F22"
fontcolor_hex: "#252525"
